"use client";

import Link from "next/link";

export default function TermsPage() {
  return (
    <main style={{ minHeight: "100vh", background: "var(--bg-primary)", color: "var(--ink-primary)" }}>
      {/* Header */}
      <header className="nav">
        <div className="nav-inner">
          <Link href="/" className="brand" style={{ color: "inherit", textDecoration: "none" }}>
            <span className="brand-icon">📥</span>
            <span>Himova</span>
          </Link>
          <nav className="nav-links">
            <Link href="/">Home</Link>
            <Link href="/privacy">Privacy</Link>
            <Link href="/terms">Terms</Link>
            <Link href="/policy">Policy</Link>
          </nav>
        </div>
      </header>

      {/* Content */}
      <div className="main-content" style={{ paddingTop: "120px", paddingBottom: "80px" }}>
        <div style={{ maxWidth: "800px", margin: "0 auto" }}>
          <h1 className="section-title" style={{ marginBottom: "40px" }}>Terms of Service</h1>

          <section style={{ marginBottom: "40px" }}>
            <h2 style={{ fontSize: "20px", fontWeight: "600", marginBottom: "12px" }}>1. Acceptance of Terms</h2>
            <p style={{ lineHeight: "1.6", color: "var(--ink-secondary)" }}>
              By using Himova, you agree to these Terms of Service. If you don't agree, please don't use our service.
            </p>
          </section>

          <section style={{ marginBottom: "40px" }}>
            <h2 style={{ fontSize: "20px", fontWeight: "600", marginBottom: "12px" }}>2. Service Description</h2>
            <p style={{ lineHeight: "1.6", color: "var(--ink-secondary)" }}>
              Himova is an AI-powered email drafting service designed for salon businesses. We analyze customer emails and generate context-aware replies based on your business data.
            </p>
          </section>

          <section style={{ marginBottom: "40px" }}>
            <h2 style={{ fontSize: "20px", fontWeight: "600", marginBottom: "12px" }}>3. User Responsibilities</h2>
            <p style={{ lineHeight: "1.6", color: "var(--ink-secondary)" }}>
              You are responsible for:
            </p>
            <ul style={{ marginTop: "12px", marginLeft: "20px", lineHeight: "1.8" }}>
              <li>Maintaining the accuracy of your salon's knowledge base</li>
              <li>Reviewing all AI-drafted replies before sending</li>
              <li>Keeping your account credentials confidential</li>
              <li>Using the service only for legitimate salon business purposes</li>
            </ul>
          </section>

          <section style={{ marginBottom: "40px" }}>
            <h2 style={{ fontSize: "20px", fontWeight: "600", marginBottom: "12px" }}>4. Limitations of Liability</h2>
            <p style={{ lineHeight: "1.6", color: "var(--ink-secondary)" }}>
              Himova provides the service "as is" without warranties. We are not liable for any indirect damages, lost profits, or business interruption resulting from use of our service.
            </p>
          </section>

          <section style={{ marginBottom: "40px" }}>
            <h2 style={{ fontSize: "20px", fontWeight: "600", marginBottom: "12px" }}>5. AI-Generated Content</h2>
            <p style={{ lineHeight: "1.6", color: "var(--ink-secondary)" }}>
              All replies generated by Himova are drafts and must be reviewed and approved by you before sending. We recommend human review, especially for low-confidence drafts.
            </p>
          </section>

          <section style={{ marginBottom: "40px" }}>
            <h2 style={{ fontSize: "20px", fontWeight: "600", marginBottom: "12px" }}>6. Payment Terms</h2>
            <p style={{ lineHeight: "1.6", color: "var(--ink-secondary)" }}>
              Himova pilot program is free during the pilot phase. Future pricing will be $15/month per location for active users.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: "20px", fontWeight: "600", marginBottom: "12px" }}>7. Contact</h2>
            <p style={{ lineHeight: "1.6", color: "var(--ink-secondary)" }}>
              Questions? Email{" "}
              <a href="mailto:support@himova.work.gd" style={{ color: "var(--brand-primary)", textDecoration: "none" }}>
                support@himova.work.gd
              </a>
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
